// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: context_engine.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the text to be processed.
type ProcessTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ProcessTextRequest) Reset() {
	*x = ProcessTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_context_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTextRequest) ProtoMessage() {}

func (x *ProcessTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTextRequest.ProtoReflect.Descriptor instead.
func (*ProcessTextRequest) Descriptor() ([]byte, []int) {
	return file_context_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// The response message containing the processed text.
type ProcessTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessedText string `protobuf:"bytes,1,opt,name=processed_text,json=processedText,proto3" json:"processed_text,omitempty"`
}

func (x *ProcessTextResponse) Reset() {
	*x = ProcessTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_context_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTextResponse) ProtoMessage() {}

func (x *ProcessTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTextResponse.ProtoReflect.Descriptor instead.
func (*ProcessTextResponse) Descriptor() ([]byte, []int) {
	return file_context_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessTextResponse) GetProcessedText() string {
	if x != nil {
		return x.ProcessedText
	}
	return ""
}

var File_context_engine_proto protoreflect.FileDescriptor

var file_context_engine_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a,
	0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3c, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x54, 0x65, 0x78, 0x74, 0x32, 0x57, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x65, 0x78, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_context_engine_proto_rawDescOnce sync.Once
	file_context_engine_proto_rawDescData = file_context_engine_proto_rawDesc
)

func file_context_engine_proto_rawDescGZIP() []byte {
	file_context_engine_proto_rawDescOnce.Do(func() {
		file_context_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_context_engine_proto_rawDescData)
	})
	return file_context_engine_proto_rawDescData
}

var file_context_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_context_engine_proto_goTypes = []interface{}{
	(*ProcessTextRequest)(nil),  // 0: proto.ProcessTextRequest
	(*ProcessTextResponse)(nil), // 1: proto.ProcessTextResponse
}
var file_context_engine_proto_depIdxs = []int32{
	0, // 0: proto.ContextEngine.ProcessText:input_type -> proto.ProcessTextRequest
	1, // 1: proto.ContextEngine.ProcessText:output_type -> proto.ProcessTextResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_context_engine_proto_init() }
func file_context_engine_proto_init() {
	if File_context_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_context_engine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_context_engine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_context_engine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_engine_proto_goTypes,
		DependencyIndexes: file_context_engine_proto_depIdxs,
		MessageInfos:      file_context_engine_proto_msgTypes,
	}.Build()
	File_context_engine_proto = out.File
	file_context_engine_proto_rawDesc = nil
	file_context_engine_proto_goTypes = nil
	file_context_engine_proto_depIdxs = nil
}
